version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: hyper
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - 386
    ignore:
      - goos: darwin
        goarch: 386
    main: ./cmd/hyper
    ldflags:
      - -s -w
      - -X github.com/sethrylan/hyper/internal/buildinfo.version={{ .Version }}
      - -X github.com/sethrylan/hyper/internal/buildinfo.distribution=release

archives:
  - ids:
      - hyper
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}"

checksum:
  name_template: hyper_checksums.txt
  extra_files:
    - glob: ./install.sh

release:
  extra_files:
    - glob: ./install.sh

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
